### ISSUE TITLE
main() missing 2 required positional arguments: 'name' and 'directory'

### ISSUE THREAD

**Issue by Mazsy** [ZurichNLP/spoken-to-signed-translation#11] opened 2023-07-31 00:05 UTC
Hi, I have the following error
TypeError: main() missing 2 required positional arguments: 'name' and 'directory'

I run this:
download_lexicon
--name signsuisse
--directory lexicon

**Comment by AmitMY** [comment] 2023-07-31 07:45
Duplicate of #10

**Closed** 2023-07-31 07:48 UTC
