### ISSUE TITLE
when I want to download lexicon,I got error

### ISSUE THREAD

**Issue by zhangrc12138** [ZurichNLP/spoken-to-signed-translation#13] opened 2023-08-17 01:34 UTC
Traceback (most recent call last):
  File "/usr/local/bin/download_lexicon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 114, in main
    add_data(data, args.directory)
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 102, in add_data
    writer.writerow([row[key] for key in LEXICON_INDEX])
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 102, in <listcomp>
    writer.writerow([row[key] for key in LEXICON_INDEX])
KeyError: 'start'
  0% 0/18222 [00:02<?, ?it/s]

I run the code in colab

**Comment by bricksdont** [comment] 2023-08-17 06:39
Duplicate of https://github.com/ZurichNLP/spoken-to-signed-translation/issues/12, closing for now

**Closed by bricksdont** 2023-08-17 06:39 UTC
